// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_tuO7G6AEffN1YLKww4y6VJESGTMBqA',
    appId: '1:838254014456:web:d9cc337f7368aadf0a300d',
    messagingSenderId: '838254014456',
    projectId: 'nata-michael',
    authDomain: 'nata-michael.firebaseapp.com',
    storageBucket: 'nata-michael.appspot.com',
    measurementId: 'G-X7D2REKZPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGjJMolPvCLAm5_oKNQhK4AMN_jhIQfIM',
    appId: '1:838254014456:android:7134d73c91aadf8d0a300d',
    messagingSenderId: '838254014456',
    projectId: 'nata-michael',
    storageBucket: 'nata-michael.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-pBIt-citfVNWjdOqoR30TeE4Jq5ay6w',
    appId: '1:838254014456:ios:67b83c8b2d221da90a300d',
    messagingSenderId: '838254014456',
    projectId: 'nata-michael',
    storageBucket: 'nata-michael.appspot.com',
    iosClientId: '838254014456-5nbl49bbkue5v6c6agp5emb9ajj902kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasKlpMichaelNata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-pBIt-citfVNWjdOqoR30TeE4Jq5ay6w',
    appId: '1:838254014456:ios:67b83c8b2d221da90a300d',
    messagingSenderId: '838254014456',
    projectId: 'nata-michael',
    storageBucket: 'nata-michael.appspot.com',
    iosClientId: '838254014456-5nbl49bbkue5v6c6agp5emb9ajj902kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasKlpMichaelNata',
  );
}
